/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class CheckinExtendedResponse (
  id: Option[Long],
  createdAt: Option[String],
  updatedAt: Option[String],
  closedAt: Option[String],
  status: Option[String],
  rating: Option[Long],
  checkinType: Option[String],
  reservation: Option[ReservationResponse],
  user: Option[String],
  venue: Option[VenueExtendedResponse],
  mobileKeys: Option[Seq[MobileKeyResponse]]
) extends ApiModel


