/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class CheckoutRequestResponse (
  id: Option[Int],
  state: Option[String],
  user: Option[UserResponse],
  venue: Option[VenueResponse],
  checkin: Option[CheckinResponse],
  creditCard: Option[CreditcardResponse],
  requestDeliverables: Option[DeliverableResponse],
  extraAmount: Option[Float],
  extraCurrency: Option[String],
  createdAt: Option[String],
  updatedAt: Option[String]
) extends ApiModel


