/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class CreditcardCreateRequest (
  lastFour: Option[Long],
  brand: Option[String],
  useCase: Option[String],
  externalCardId: Option[String],
  businessName: Option[String],
  provider: Option[CreditcardCreateRequestEnums.Provider]
) extends ApiModel

object CreditcardCreateRequestEnums {

  type Provider = Provider.Value
  object Provider extends Enumeration {
    val SumUp = Value("sum_up")
    val Payleven = Value("payleven")
  }

}

