/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class MobileKeyResponse (
  id: Option[Long],
  checkinId: Option[Long],
  userId: Option[Long],
  guestSessionId: Option[Long],
  serverKeyId: Option[Int],
  roomName: Option[String],
  startDate: Option[String],
  endDate: Option[String],
  provider: Option[MobileKeyResponseEnums.Provider],
  status: Option[MobileKeyResponseEnums.Status]
) extends ApiModel

object MobileKeyResponseEnums {

  type Provider = Provider.Value
  type Status = Status.Value
  object Provider extends Enumeration {
    val AssaAbloy = Value("assa_abloy")
    val Messerschmit = Value("messerschmit")
    val Onity = Value("onity")
    val Hafele = Value("hafele")
  }

  object Status extends Enumeration {
    val Issued = Value("issued")
    val Received = Value("received")
    val Revoked = Value("revoked")
  }

}

