/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class PrecheckinRequestRequest (
  venueId: Option[Long],
  arrivedOn: Option[Date],
  departedOn: Option[Date],
  arriveTime: Option[PrecheckinRequestRequestEnums.ArriveTime],
  deliverableItems: Option[Seq[PrecheckinRequestRequestDeliverableItems]],
  reservationNumber: Option[Long],
  roomType: Option[String],
  /* L - Leisure B - Business  */
  travelPurpose: Option[PrecheckinRequestRequestEnums.TravelPurpose],
  /* if not provided, mobile will be assumed */
  comingFrom: Option[PrecheckinRequestRequestEnums.ComingFrom]
) extends ApiModel

object PrecheckinRequestRequestEnums {

  type ArriveTime = ArriveTime.Value
  type TravelPurpose = TravelPurpose.Value
  type ComingFrom = ComingFrom.Value
  object ArriveTime extends Enumeration {
    val EarlyMorning = Value("early_morning")
    val Morning = Value("morning")
    val Midday = Value("midday")
    val Afternoon = Value("afternoon")
    val Evening = Value("evening")
    val Night = Value("night")
  }

  object TravelPurpose extends Enumeration {
    val `L` = Value("L")
    val `B` = Value("B")
  }

  object ComingFrom extends Enumeration {
    val Mobile = Value("mobile")
    val Web = Value("web")
  }

}

