/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class PrecheckinRequestResponse (
  id: Option[Long],
  venue: Option[VenueResponse],
  arrivedOn: Option[Date],
  departedOn: Option[Date],
  status: Option[String],
  arriveTime: Option[String],
  precheckinRequestDeliverables: Option[Seq[RequestDeliverable]],
  createdAt: Option[String],
  updatedAt: Option[String],
  reservationNumber: Option[Long],
  roomType: Option[String],
  travelPurpose: Option[String]
) extends ApiModel


