/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ProfileRequest (
  firstName: Option[String],
  lastName: Option[String],
  email: Option[String],
  gender: Option[String],
  locale: Option[String],
  birthDate: Option[String],
  nationality: Option[String],
  plvToken: Option[String],
  businessName: Option[String],
  businessStreet: Option[String],
  businessZip: Option[String],
  businessCity: Option[String],
  businessCountryCode: Option[String],
  streetName: Option[String],
  zip: Option[String],
  cityName: Option[String],
  countryCode: Option[String],
  documentType: Option[String],
  documentNumber: Option[String],
  documentDoi: Option[String],
  documentAuthority: Option[String],
  cityOfBirth: Option[String],
  countryOfBirth: Option[String],
  taxIdentificationNumber: Option[String],
  taxOfficeName: Option[String]
) extends ApiModel


