/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ReservationResponse (
  id: Option[Long],
  userId: Option[Long],
  venueId: Option[Long],
  confirmationId: Option[String],
  reservationNumber: Option[Long],
  checkinDate: Option[Date],
  checkoutDate: Option[Date],
  totalStayAmount: Option[Float],
  openBalance: Option[Float],
  currencyCode: Option[String],
  roomNumber: Option[Long],
  guests: Option[Seq[Guests]],
  notSyncedAmount: Option[Float],
  checkinIsAvailable: Option[Boolean],
  notifyMe: Option[Boolean],
  reservationInfo: Option[String],
  clientNumber: Option[Long],
  status: Option[String],
  outstandingAmount: Option[Float],
  checkinId: Option[Long]
) extends ApiModel


