/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class StayResponse (
  arrivalDate: Option[Date],
  departureDate: Option[Date],
  reservationNumber: Option[String],
  mobileCheckin: Option[Boolean],
  completed: Option[Boolean],
  rating: Option[Double],
  checkinId: Option[Double],
  venue: Option[VenueResponse],
  precheckinRequest: Option[PrecheckinRequestResponse]
) extends ApiModel


