/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class TrackinResponse (
  id: Option[Int],
  createdAt: Option[String],
  updatedAt: Option[String],
  closedAt: Option[String],
  status: Option[TrackinResponseEnums.Status],
  user: Option[UserResponse],
  region: Option[RegionResponse],
  reservation: Option[ReservationResponse]
) extends ApiModel

object TrackinResponseEnums {

  type Status = Status.Value
  object Status extends Enumeration {
    val Open = Value("open")
    val Closed = Value("closed")
  }

}

