/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class UserNotificationResponse (
  id: Option[Int],
  createdAt: Option[String],
  updatedAt: Option[String],
  read: Option[Boolean],
  favourite: Option[Boolean],
  welcomeMessage: Option[String],
  icon: Option[String],
  `type`: Option[UserNotificationResponseEnums.&#x60;Type&#x60;],
  title: Option[String],
  venueName: Option[String]
) extends ApiModel

object UserNotificationResponseEnums {

  type &#x60;Type&#x60; = &#x60;Type&#x60;.Value
  object &#x60;Type&#x60; extends Enumeration {
    val Checkin = Value("checkin")
    val Checkout = Value("checkout")
    val PaymentCompleted = Value("payment_completed")
    val PaymentDenied = Value("payment_denied")
    val Custom = Value("custom")
    val Conichi = Value("conichi")
    val OpenCheckin = Value("open_checkin")
    val ClosedCheckin = Value("closed_checkin")
    val OpenTrackin = Value("open_trackin")
    val ClosedTrackin = Value("closed_trackin")
    val NewCheckoutRequest = Value("new_checkout_request")
    val CompletedTransaction = Value("completed_transaction")
    val AbortedTransaction = Value("aborted_transaction")
  }

}

