/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class UserExtendedResponse (
  id: Option[Long],
  firstName: Option[String],
  lastName: Option[String],
  name: Option[String],
  email: Option[String],
  gender: Option[String],
  birthDate: Option[String],
  locale: Option[String],
  provider: Option[String],
  profilePhoto: Option[String],
  plvToken: Option[String],
  optValue: Option[UserResponseOptValue],
  createdAt: Option[String],
  nationality: Option[String],
  travelDocument: Option[String],
  preferences: Option[Seq[Preference]],
  address: Option[Location],
  businessAddress: Option[LocationBusiness],
  cityTax: Option[CityTax],
  creditCards: Option[Seq[CreditcardResponse]],
  corporate: Option[Corporate]
) extends ApiModel


