/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class VenueCardResponse (
  id: Option[Long],
  createdAt: Option[String],
  updatedAt: Option[String],
  name: Option[String],
  footer: Option[String],
  position: Option[Int],
  photoUrl: Option[String],
  iconUrl: Option[String],
  category: Option[VenueCardResponseEnums.Category],
  sections: Option[Seq[VenueCardSectionResponse]]
) extends ApiModel

object VenueCardResponseEnums {

  type Category = Category.Value
  object Category extends Enumeration {
    val Info = Value("info")
    val Fitness = Value("fitness")
    val Food = Value("food")
    val Defaut = Value("defaut")
  }

}

