/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class VenueExtendedResponse (
  id: Option[Long],
  createdAt: Option[String],
  updatedAt: Option[String],
  name: Option[String],
  major: Option[Long],
  welcomeMessage: Option[String],
  farewellMessage: Option[String],
  status: Option[String],
  starsNumber: Option[Long],
  paymentEnabled: Option[Boolean],
  uuid: Option[String],
  cityTaxReady: Option[Boolean],
  pmsIntegrated: Option[Boolean],
  keyProvider: Option[String],
  photo: Option[String],
  externalKeyProviderCode: Option[String],
  location: Option[Location],
  contact: Option[Contact],
  regions: Option[Seq[VenueCardResponse]],
  cards: Option[Seq[VenueCardResponse]]
) extends ApiModel


